name: Daily Commit

on:
  schedule:
    - cron: '15 4 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository - 23f3001244@ds.study.iitm.ac.in
        uses: actions/checkout@v3

      #- name: Commit step 
      #  run: |
      #    echo "Daily run: $(date -u)" >> daily-log.txt

      - name: Git Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Auto commit at $(date -u)" || echo "No changes to commit"
          git push