name: Main

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository - 23f3001244@ds.study.iitm.ac.in
        uses: actions/checkout@v3

      - name: Commit step 
        run: |
          echo "Daily run: $(date -u)" >> logs.txt

      - name: Git Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add logs.txt
          git commit -m "Auto commit at $(date -u)" || echo "No changes to commit"
          git push
